<?php

namespace familleBundle\Repository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use \Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findusersbyrole($roles)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('UserBundle:User', 'u')
            ->where("u.roles LIKE :roles")
            ->setParameter('roles', '%"'.$roles.'"%');

        return $qb->getQuery()->getResult();

    }
    public function getuserdatabyUsername($user_name)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('UserBundle:User', 'u')
            ->where('u.username LIKE :username')
            ->setParameter('username', $user_name);
        return $qb->getQuery()->getResult();

    }



    public function getuserdatabyUsername2()
    {
        $q = $this->getEntityManager()->createQuery("SELECT u from UserBundle:User u where u.roles='ROLE_ASSOCIATION' " );
        return $query = $q->getResult();
    }
    public function findloginEnvoi($loginEnvoi){

        $q = $this->getEntityManager()->createQuery("SELECT  p.username ,p.image from UserBundle:User p where p.roles='a:1:{i:0;s:16:\"ROLE_ASSOCIATION\";}' and (p.username !=:loginenvoi) " )
            ->setParameter('loginenvoi',$loginEnvoi);

        return $query = $q->getResult();
    }

    public function findloginEnvoi2(){

        $q = $this->getEntityManager()->createQuery("SELECT distinct p from familleBundle:message p where p.role='Association' " );

        return $query = $q->getResult();
    }

public function getMesage(  $loginenvoi , $loginrecep ){
        $q = $this -> getEntityManager()->createQuery("SELECT u FROM familleBundle:message u
             where
               (u.loginEnvoi =:loginenvoi or u.loginEnvoi =:loginrecep )
             and( u.loginRecep =:loginenvoi or u.loginRecep =:loginrecep ) order by u.date  ")
       //     ->setParameter('idenvoi',$idenvoi)
          //  ->setParameter('idrecep',$idrecep)
            ->setParameter('loginenvoi',$loginenvoi)
            ->setParameter('loginrecep',$loginrecep)

;

        return $query = $q -> getResult();
}

    public function getimg(   $loginrecep ){
        $q = $this->getEntityManager()->createQuery("SELECT  p.image from UserBundle:User p where  p.username =:loginenvoi " )
            ->setParameter('loginenvoi',$loginrecep);

        ;

        return $query = $q -> getResult();
    }

    public function findIdByUsername($loginRecep)
    {
        $q = $this->getEntityManager()->createQuery("SELECT u.idRecep from familleBundle:message u where u.loginRecep=:loginRecep " )
            ->setParameter('loginRecep',$loginRecep)
        ;
        return $query = $q->getResult();
    }

    public function imagemessage( $loginenvoi){
        $q = $this->getEntityManager()->createQuery("SELECT u from UserBundle:User u where u.login=:loginRecep " )
            ->setParameter('login',$loginenvoi)
        ;
        return $query = $q->getResult();


    }


}
