<?php

namespace ActualiteBundle\Repository;

/**
 * fosmobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fosmobileRepository extends \Doctrine\ORM\EntityRepository
{
    public function cnx($login_db,$mdp_db)
    {
        $q =$this->getEntityManager()
            ->createQuery(
                'SELECT p from ActualiteBundle:fosmobile p where p.mdp_db =:mdp_db and p.login_db =:str'
            )
            ->setParameter('str', $login_db)
            ->setParameter('mdp_db', $mdp_db);
        $query = $q->getResult();

        return $query;
    }
    public function findfosbyusername($login_db)
    {
        $q = $this->getEntityManager()->createQuery("SELECT s from ActualiteBundle:fosmobile s where s.login_db=:login_db " )
            ->setParameter('login_db',$login_db);
        $query = $q->getResult();

        return $query;
    }
}

