imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@familleBundle/Resources/config/services.yml" }
    - { resource: "@AssoBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@adminBundle/Resources/config/services.yml" }
    - { resource: "@RefugeeBundle/Resources/config/services.yml" }
    - { resource: "@LivBundle/Resources/config/services.yml" }
    - { resource: "@sponsBundle/Resources/config/services.yml" }
    - { resource: "@stockBundle/Resources/config/services.yml" }
    - { resource: "@ForumBundle/Resources/config/services.yml" }
    - { resource: "@eventBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    image_directory : '%kernel.project_dir%/web/upload'

framework:
    #esi: ~
    templating:
      engines: ['twig']
    translator: ~
    secret: '%secret%'
    router:

        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    auth_mode:        login
    port:             25
    encryption:       tls
    source_ip:    127.0.0.1
    spool: { type: memory }
sensio_framework_extra:
   router:
        annotations: false
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            from_email:
                address:        "wadie.belghith1@esprit.com"
                sender_name:    "wadie"
    registration:
        confirmation:
            from_email:
                address:        "wadie.belghith1@esprit.com"
                sender_name:    "wadie"
    from_email:
        address: "wadie.belghith1@esprit.com"
        sender_name: "wadie"

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
notifications:
    app_id:     982240
    app_key:    bd5e41387c3f32e217ca
    app_secret: d630011f6d7e55855f0e
    cluster:    ap2
    # Optional
    # Default false: work without ssl encryption
    # Set it to true to work with ssl encryption
    encrypted:  false
nomaya_social:
  buttons:
    facebook:
      url: "https://www.facebook.com/wa.be.77"
      locale: "fr_FR"
      send: false
      width: 300
      showFaces: true
      layout: "button_count"
    twiter:
      url:
      locale: "fr"
      message: " JE veux "
      text: "Tweet"
      via : "Esprit Test"
      tag: "Esprit"
    linkedin:
      url: "https://www.linkedin.com/in/wadiebelghith15/"
      locale: "fr"
      counter: "right"
  theme:  'default'
knp_snappy:
  pdf:
    enabled:    true
    binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
    options:    []
  image:
    enabled:    true
    binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
    options:    []
  temporary_folder: %kernel.cache_dir%/snappy



