<?php

namespace eventBundle\Repository;

/**
 * participRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participRepository extends \Doctrine\ORM\EntityRepository
{
    public function findparticipbyidevent($id)
    {
        $q = $this->getEntityManager()->createQuery("SELECT p from eventBundle:particip p where p.idevent=:id " )
            ->setParameter('id',$id);
        $query = $q->getResult();

        return $query;
    }
}
