<?php

namespace ForumBundle\Repository;

/**
 * ReponsercRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponsercRepository extends \Doctrine\ORM\EntityRepository
{
}
